### ISSUE TITLE
Some questions about the proposal method

### ISSUE THREAD

**Issue by floatingstarZ** [liming-ai/AlignDet#1]
Hello, this research is truly valuable and interesting. What I am curious about is whether the authors have tried using the ground truth annotations from the COCO training set as proposals for pre-training. Since the COCO annotations are more accurate, I guess using more accurate annotations might improve the effectiveness of pre-training.

**Comment by liming-ai** [comment]
> 

Thank you for your interest in our work!  We did use the ground truth annotations to pre-train the neck & head, and its performance is higher than the unsupervised annotations, but we did not dig into this.

In fact, pre-training the neck & head with ground truth annotations is a kind of pre-experiment, we explored the unsupervised settings after we verified "it is effective to pre-train the neck & head".

However, since AlignDet focuses on the self-supervised setting, we do not conduct experiments on supervised pre-training, since some big detection datasets have verified the effectiveness of large-scale pre-training with ground truth annotations, like Objects365, BigDetection, and OpenImages.

**Comment by floatingstarZ** [comment]
> > 
> 
> Thank you for your interest in our work! We did use the ground truth annotations to pre-train the neck & head, and its performance is higher than the unsupervised annotations, but we did not dig into this.
> 
> In fact, pre-training the neck & head with ground truth annotations is a kind of pre-experiment, we explored the unsupervised settings after we verified "it is effective to pre-train the neck & head".
> 
> However, since AlignDet focuses on the self-supervised setting, we do not conduct experiments on supervised pre-training, since some big detection datasets have verified the effectiveness of large-scale pre-training with ground truth annotations, like Objects365, BigDetection, and OpenImages.

Thank you~
