### ISSUE TITLE
Hi,how can i get proposals with cluster info in detr

### ISSUE THREAD

**Issue by Minorant** [liming-ai/AlignDet#13]
Hi, thanks for your impressive work!
I'm trying to run DETR on the VOC dataset, but I notice that only coco's post-clustering proposal is provided([train2017_ratio3size0008@0.5_cluster-id-as-class.json](mailto:train2017_ratio3size0008@0.5_cluster-id-as-class.json)). So how can I generate my own post clustering proposal? Is there any code available or more detailed steps for this please, thanks!

**Comment by liming-ai** [comment]
> Hi, thanks for your impressive work! I'm trying to run DETR on the VOC dataset, but I notice that only coco's post-clustering proposal is provided([train2017_ratio3size0008@0.5_cluster-id-as-class.json](mailto:train2017_ratio3size0008@0.5_cluster-id-as-class.json)). So how can I generate my own post clustering proposal? Is there any code available or more detailed steps for this please, thanks!

Hi, thanks for your interest in AlignDet~

Since AlignDet is pre-trained on COCO, so we only provide the clustered proposals on COCO. When fine-tuning the pre-trained model on VOC, we have the ground truth annotations.

Unfortunately, we cannot release the code for the clustering proposal, but this procedure should be simple:

1. Running the selective search algorithm (Please refer to [SoCo](https://github.com/hologerry/SoCo/tree/main/selective_search)) to obtain unsupervised proposals.
2. Extracting the features of these proposals with RoI Align operation (Can be done with supervised/unsupervised backbone)
3. Performing PCA algorithm to reduce the dimension of features (We use the dimension of 256, but others should also be fine)
4. Using the K-means algorithm to cluster these proposals.

Thanks again for your question, I hope it can help you~
